package main.java.constants;

public enum LTAgentID {
	CLIENT_AGENT, AUTHENTICATION_AGENT, SOC_NET_AGENT, LOGIN_AGENT, REGISTER_AGENT, VERIFY_AGENT, RESET_AGENT, CHAT_AGENT, FRIENDSHIP_AGENT, PINBOARD_AGENT
}
